user_input = input('Digite algo: ')
print(f'O tipo primitivo desse valor é: {type(user_input)}')
print(f'Só tem espaços: {user_input.isspace()}')
print(f'É número: {user_input.isnumeric()}')
print(f'É alfabético: {user_input.isalpha()}')
print(f'É alfanumérico: {user_input.isalnum()}')
print(f'Está maiúsculas: {user_input.isupper()}')
print(f'Está minúscula: {user_input.islower()}')
print(f'Está capitalizada: {user_input.istitle()}')