let num1='150'
let flo1='1.50'
console.log('=========Converting string to integers=========')
console.log(typeof num1)
console.log(typeof flo1)
console.log(typeof parseInt(num1))
console.log(typeof parseFloat(flo1))
console.log('')
console.log(num1)
console.log(Number(num1))
console.log('')
console.log(flo1)
console.log(Number(flo1))
console.log('')
console.log(Number('abc'))
console.log(Number('0xF'))
console.log('')
console.log('=========More Conversions=========')
//numbers after special charactersare ignored
console.log(Number('1.5'))
console.log(parseInt('1.5'))
console.log(Number('1+1'))
console.log(parseInt('1+1'))
console.log('')
//using template literals
console.log(parseInt(`${1+1}`))
console.log('')
console.log('=========Converting integers to string=========')
console.log(typeof (100).toString())
console.log((100).toString())